name: ECO-CI Energy Measurement

on: [push]

jobs:
  measure-energy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Initialize ECO-CI
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement

      - name: Execute Script
        run: python primes.py

      - name: Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'Ejecuci√≥n Algoritmo Primos'

      - name: Finalize and Display Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          calculate-co2: true
          electricitymaps-api-token: ${{ secrets.ELECTRICITY_MAPS_TOKEN }}
          send-data: true
          project: 'primos-test'
          display-table: true
